repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: [-c, pyproject.toml]
        additional_dependencies: [bandit[toml]]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
      - id: pylint
        name: pylint
        entry: pylint app.py utils pages
        language: system
        pass_filenames: false
      - id: vulture
        name: vulture
        entry: vulture app.py utils pages --min-confidence 80
        language: system
        pass_filenames: false
      - id: pip-audit
        name: pip-audit
        entry: pip-audit -r requirements.txt
        language: system
        pass_filenames: false
      - id: semgrep
        name: semgrep
        entry: semgrep --config .semgrep.yml
        language: system
        pass_filenames: false
